import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faUserCog,
  faUsers,
  faHatCowboy,
  faLock,
  faMagic,
  faCogs,
  faThLarge,
  faPen,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faPowerOff,
  faCheck,
  faTachometerAlt,
  faTimes,
  faPlus,
} from '@fortawesome/free-solid-svg-icons'

library.add(
  faUserCog,
  faUsers,
  faHatCowboy,
  faLock,
  faMagic,
  faCogs,
  faThLarge,
  faPen,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faPowerOff,
  faCheck,
  faTachometerAlt,
  faTimes,
  faPlus,
)
