import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faUserCog,
  faUsers,
  faHatCowboy,
  faLock,
  faMagic,
  faCogs,
  faThLarge,
  faPen,
  faAngleDoubleRight,
  faPowerOff,
  faCheck,
  faTachometerAlt,
  faTimes,
  faPlus,
  faSlidersH,
  faGlasses,
  faShareAlt,
  faExclamationTriangle,
  faFolder,
  faSync,
  faEye,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleLeft,
} from '@fortawesome/free-solid-svg-icons'

import {
  faCopy,
  faCheckCircle,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faUserCog,
  faUsers,
  faHatCowboy,
  faLock,
  faMagic,
  faCogs,
  faThLarge,
  faPen,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faPowerOff,
  faCheck,
  faTachometerAlt,
  faTimes,
  faPlus,
  faSlidersH,
  faGlasses,
  faShareAlt,
  faCopy,
  faCheckCircle,
  faExclamationTriangle,
  faFolder,
  faSync,
  faEye,
  faAngleRight,
  faAngleLeft,
)
